# .github/workflows/deployment.yml
 
name: Deploy React App to Azure App Service with Credentials
 
# Trigger the workflow on push to main branch or manual trigger
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering
 
# Environment variables available throughout the workflow
env:
  AZURE_WEBAPP_NAME: ai-for-ui    # Replace with your Azure App Service name
  AZURE_WEBAPP_PACKAGE_PATH: './build'        # Path to the built React app
  NODE_VERSION: '18.x'                        # Node.js version to use
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4
 
      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'  # Cache npm dependencies for faster builds
 
      # Install dependencies and build the React app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
      - name: Print Environment Variables
        run: |
          echo "AZURE_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}"
          echo "AZURE_CLIENT_SECRET: ${{ env.AZURE_CLIENT_SECRET }}"
          echo "AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}"
          echo "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      # Log in to Azure using credentials
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }
 
      # Deploy to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
 
      # Optional: Logout from Azure
      - name: Azure Logout
        run: az logout
        if: always()  # Runs even if previous steps fail
 
      # Optional: Output the deployment URL
      - name: Output deployment URL
        run: echo "App deployed to https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
