# .github/workflows/deployment.yml

name: Deploy React App to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

env:
  AZURE_WEBAPP_NAME: ai-for-ui  # Replace with your Azure App Service name
  AZURE_WEBAPP_PACKAGE_PATH: './build' # Path to the built React app
  NODE_VERSION: '18.x' # Node.js version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Install dependencies and build the React app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present

      # Upload artifact for debugging (Optional)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/


      # 🔹 Use Azure Publish Profile (Recommended)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Optional: Logout from Azure
      - name: Azure Logout
        run: az logout
        if: always()  # Runs even if previous steps fail

      # Optional: Output deployment URL
      - name: Output deployment URL
        run: echo "App deployed to https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
